-- Ermi Pengantin customer journey v2
-- Idempotent migration. Run this on a staging copy before production.
BEGIN;

CREATE SCHEMA IF NOT EXISTS private;

CREATE TABLE IF NOT EXISTS public.admin_users (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  role TEXT NOT NULL DEFAULT 'admin' CHECK (role IN ('admin', 'superadmin')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Compatibility bootstrap: only users that already existed when this migration
-- is applied become admins. New authenticated users are not admins automatically.
INSERT INTO public.admin_users (user_id, email, role)
SELECT id, email, 'admin' FROM auth.users
ON CONFLICT (user_id) DO NOTHING;

CREATE OR REPLACE FUNCTION private.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$ SELECT EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = auth.uid()) $$;

REVOKE ALL ON FUNCTION private.is_admin() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION private.is_admin() TO authenticated;

ALTER TABLE public.admin_users ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Admins can read admin registry" ON public.admin_users;
CREATE POLICY "Admins can read admin registry" ON public.admin_users
  FOR SELECT TO authenticated USING (private.is_admin());

CREATE TABLE IF NOT EXISTS public.dress_units (
  id UUID PRIMARY KEY,
  dress_id TEXT NOT NULL REFERENCES public.dresses(id) ON DELETE RESTRICT,
  unit_code TEXT NOT NULL UNIQUE,
  size TEXT NOT NULL,
  color TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'ready' CHECK (status IN ('ready', 'maintenance', 'retired')),
  notes TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.booking_dress_assignments (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id TEXT NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  dress_unit_id UUID NOT NULL REFERENCES public.dress_units(id) ON DELETE RESTRICT,
  rental_start DATE NOT NULL,
  rental_end DATE NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT booking_assignment_period CHECK (rental_end >= rental_start),
  UNIQUE (booking_id, dress_unit_id)
);

CREATE INDEX IF NOT EXISTS booking_assignment_unit_period_idx
  ON public.booking_dress_assignments (dress_unit_id, rental_start, rental_end);

CREATE TABLE IF NOT EXISTS public.payment_submissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id TEXT NOT NULL REFERENCES public.bookings(id) ON DELETE CASCADE,
  payment_type TEXT NOT NULL CHECK (payment_type IN ('dp', 'full', 'settlement')),
  payment_method TEXT NOT NULL DEFAULT '',
  amount BIGINT NOT NULL CHECK (amount > 0),
  object_path TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'under_review' CHECK (status IN ('under_review', 'approved', 'rejected')),
  rejection_reason TEXT,
  reviewer_id UUID REFERENCES public.admin_users(user_id),
  reviewed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.booking_access_audit (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ip_address TEXT NOT NULL,
  invoice_number TEXT NOT NULL,
  success BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS booking_access_audit_rate_idx
  ON public.booking_access_audit (created_at, ip_address, invoice_number);

CREATE TABLE IF NOT EXISTS public.payment_proof_migration_queue (
  booking_id TEXT PRIMARY KEY REFERENCES public.bookings(id) ON DELETE CASCADE,
  legacy_public_url TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'migrated', 'failed')),
  private_object_path TEXT,
  validated_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
INSERT INTO public.payment_proof_migration_queue (booking_id, legacy_public_url)
SELECT id, payment_proof FROM public.bookings
WHERE payment_proof IS NOT NULL AND payment_proof <> ''
ON CONFLICT (booking_id) DO NOTHING;

ALTER TABLE public.bookings
  ADD COLUMN IF NOT EXISTS access_token_hash TEXT,
  ADD COLUMN IF NOT EXISTS payment_due_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS rental_start DATE,
  ADD COLUMN IF NOT EXISTS rental_end DATE,
  ADD COLUMN IF NOT EXISTS admin_notes TEXT;

-- New rows store integer rupiah. Legacy formatted strings are normalized.
ALTER TABLE public.bookings ALTER COLUMN subtotal DROP DEFAULT;
ALTER TABLE public.bookings ALTER COLUMN additional_fees DROP DEFAULT;
ALTER TABLE public.bookings ALTER COLUMN deposit_required DROP DEFAULT;
ALTER TABLE public.bookings ALTER COLUMN total_amount DROP DEFAULT;
ALTER TABLE public.bookings ALTER COLUMN subtotal TYPE BIGINT USING COALESCE(NULLIF(regexp_replace(subtotal, '[^0-9-]', '', 'g'), ''), '0')::BIGINT;
ALTER TABLE public.bookings ALTER COLUMN additional_fees TYPE BIGINT USING COALESCE(NULLIF(regexp_replace(additional_fees, '[^0-9-]', '', 'g'), ''), '0')::BIGINT;
ALTER TABLE public.bookings ALTER COLUMN deposit_required TYPE BIGINT USING COALESCE(NULLIF(regexp_replace(deposit_required, '[^0-9-]', '', 'g'), ''), '0')::BIGINT;
ALTER TABLE public.bookings ALTER COLUMN total_amount TYPE BIGINT USING COALESCE(NULLIF(regexp_replace(total_amount, '[^0-9-]', '', 'g'), ''), '0')::BIGINT;
ALTER TABLE public.bookings ALTER COLUMN customer_email SET DEFAULT '';
ALTER TABLE public.bookings ALTER COLUMN customer_address SET DEFAULT '';
ALTER TABLE public.bookings ALTER COLUMN payment_type SET DEFAULT 'dp';
ALTER TABLE public.bookings ALTER COLUMN payment_method SET DEFAULT '';
ALTER TABLE public.bookings ALTER COLUMN payment_status SET DEFAULT 'not_due';
ALTER TABLE public.bookings ALTER COLUMN booking_status SET DEFAULT 'submitted';

-- Remove all direct public booking access. Customer access is mediated by server APIs.
DROP POLICY IF EXISTS "Allow public insert to bookings" ON public.bookings;
DROP POLICY IF EXISTS "Allow public select to bookings" ON public.bookings;
DROP POLICY IF EXISTS "Allow public update to bookings" ON public.bookings;
DROP POLICY IF EXISTS "Allow authenticated full access to bookings" ON public.bookings;
DROP POLICY IF EXISTS "Admins manage bookings" ON public.bookings;
CREATE POLICY "Admins manage bookings" ON public.bookings
  FOR ALL TO authenticated USING (private.is_admin()) WITH CHECK (private.is_admin());

ALTER TABLE public.dress_units ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_dress_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_access_audit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_proof_migration_queue ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins manage dress units" ON public.dress_units;
CREATE POLICY "Admins manage dress units" ON public.dress_units FOR ALL TO authenticated
  USING (private.is_admin()) WITH CHECK (private.is_admin());
DROP POLICY IF EXISTS "Admins manage assignments" ON public.booking_dress_assignments;
CREATE POLICY "Admins manage assignments" ON public.booking_dress_assignments FOR ALL TO authenticated
  USING (private.is_admin()) WITH CHECK (private.is_admin());
DROP POLICY IF EXISTS "Admins manage payment submissions" ON public.payment_submissions;
CREATE POLICY "Admins manage payment submissions" ON public.payment_submissions FOR ALL TO authenticated
  USING (private.is_admin()) WITH CHECK (private.is_admin());

-- Public catalog options expose only aggregate size/color availability, never unit identity.
CREATE OR REPLACE VIEW public.public_dress_options
WITH (security_invoker = false)
AS
SELECT dress_id, array_agg(DISTINCT size ORDER BY size) AS sizes,
       array_agg(DISTINCT color ORDER BY color) AS colors
FROM public.dress_units WHERE status = 'ready' GROUP BY dress_id;
REVOKE ALL ON public.public_dress_options FROM PUBLIC;
GRANT SELECT ON public.public_dress_options TO anon, authenticated;

-- Restrict catalog/settings mutations to registered admins while preserving public reads.
DO $$
DECLARE table_name TEXT;
BEGIN
  FOREACH table_name IN ARRAY ARRAY['dresses','makeup_packages','decor_packages','wedding_packages','gallery','testimonials','system_settings']
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS "Allow authenticated full access to %s" ON public.%I', table_name, table_name);
    EXECUTE format('DROP POLICY IF EXISTS "Admins manage %s" ON public.%I', table_name, table_name);
    EXECUTE format('CREATE POLICY "Admins manage %s" ON public.%I FOR ALL TO authenticated USING (private.is_admin()) WITH CHECK (private.is_admin())', table_name, table_name);
  END LOOP;
END $$;

INSERT INTO storage.buckets (id, name, public)
VALUES ('payment-proofs-private', 'payment-proofs-private', false)
ON CONFLICT (id) DO UPDATE SET public = false;

DROP POLICY IF EXISTS "Admins read private payment proofs" ON storage.objects;
CREATE POLICY "Admins read private payment proofs" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'payment-proofs-private' AND private.is_admin());

CREATE OR REPLACE FUNCTION public.confirm_booking_with_units(
  p_booking_id TEXT,
  p_admin_id UUID,
  p_unit_ids UUID[],
  p_rental_start DATE,
  p_rental_end DATE,
  p_additional_fees BIGINT,
  p_total_amount BIGINT,
  p_deposit_required BIGINT,
  p_payment_due_at TIMESTAMPTZ DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  current_booking public.bookings%ROWTYPE;
  unit_id UUID;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.admin_users WHERE user_id = p_admin_id) THEN
    RAISE EXCEPTION 'Admin tidak terdaftar';
  END IF;
  IF p_rental_end < p_rental_start THEN RAISE EXCEPTION 'Periode sewa tidak valid'; END IF;

  SELECT * INTO current_booking FROM public.bookings WHERE id = p_booking_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Booking tidak ditemukan'; END IF;
  IF current_booking.booking_status NOT IN ('submitted', 'pending') THEN
    RAISE EXCEPTION 'Booking sudah diproses';
  END IF;
  IF (current_booking.services_selected ? 'dresses' OR current_booking.services_selected ? 'weddingPackage')
     AND COALESCE(cardinality(p_unit_ids), 0) = 0 THEN
    RAISE EXCEPTION 'Pilih minimal satu unit busana';
  END IF;

  FOREACH unit_id IN ARRAY COALESCE(p_unit_ids, ARRAY[]::UUID[])
  LOOP
    PERFORM pg_advisory_xact_lock(hashtextextended(unit_id::TEXT, 0));
    IF NOT EXISTS (SELECT 1 FROM public.dress_units WHERE id = unit_id AND status = 'ready') THEN
      RAISE EXCEPTION 'Unit % tidak ready', unit_id;
    END IF;
    IF EXISTS (
      SELECT 1 FROM public.booking_dress_assignments assignment
      JOIN public.bookings booking ON booking.id = assignment.booking_id
      WHERE assignment.dress_unit_id = unit_id
        AND booking.booking_status IN ('confirmed', 'fitting', 'ready')
        AND assignment.rental_start <= p_rental_end
        AND assignment.rental_end >= p_rental_start
    ) THEN
      RAISE EXCEPTION 'Unit % bentrok pada periode tersebut', unit_id;
    END IF;
  END LOOP;

  FOREACH unit_id IN ARRAY COALESCE(p_unit_ids, ARRAY[]::UUID[])
  LOOP
    INSERT INTO public.booking_dress_assignments (booking_id, dress_unit_id, rental_start, rental_end)
    VALUES (p_booking_id, unit_id, p_rental_start, p_rental_end);
  END LOOP;

  UPDATE public.bookings SET
    booking_status = 'confirmed', payment_status = 'awaiting_payment',
    rental_start = p_rental_start, rental_end = p_rental_end,
    additional_fees = GREATEST(0, p_additional_fees),
    total_amount = GREATEST(0, p_total_amount),
    deposit_required = LEAST(GREATEST(0, p_deposit_required), GREATEST(0, p_total_amount)),
    payment_due_at = p_payment_due_at
  WHERE id = p_booking_id;

  RETURN (SELECT to_jsonb(booking) FROM public.bookings booking WHERE id = p_booking_id);
END;
$$;
REVOKE ALL ON FUNCTION public.confirm_booking_with_units(TEXT,UUID,UUID[],DATE,DATE,BIGINT,BIGINT,BIGINT,TIMESTAMPTZ) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.confirm_booking_with_units(TEXT,UUID,UUID[],DATE,DATE,BIGINT,BIGINT,BIGINT,TIMESTAMPTZ) TO service_role;

COMMIT;

-- Operational follow-up for legacy public proofs:
-- copy each payment_proof_migration_queue.legacy_public_url into the private bucket,
-- verify checksum/readability, set status='migrated' + private_object_path, then delete
-- the old public object. The app never serves legacy URLs after this migration.
